import { minify } from "html-minifier-terser";
import fs from "node:fs/promises";
import path from "node:path";

const ERROR_HTML_PATH = path.join(import.meta.dirname, "../src/fallback-error.html");
const LOADING_HTML_PATH = path.join(import.meta.dirname, "../src/fallback-loading.html");
const SPINNER_HTML_PATH = path.join(import.meta.dirname, "../src/spinner.html");
const OUTPUT_PATH = path.join(import.meta.dirname, "../src/common/fallbackHtml.generated.ts");

const minifyOptions = {
  collapseWhitespace: true,
  minifyCSS: true,
  minifyJS: true,
  removeComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  useShortDoctype: true,
};

const escapeTemplate = (str: string): string => str.replaceAll("`", "\\`").replaceAll("${", "\\${");

export async function generateFallback() {
  const [errorHtml, loadingHtml, spinnerHtml] = await Promise.all([
    fs.readFile(ERROR_HTML_PATH, "utf8"),
    fs.readFile(LOADING_HTML_PATH, "utf8"),
    fs.readFile(SPINNER_HTML_PATH, "utf8"),
  ]);

  const [errorMinified, loadingMinified, spinnerMinified] = await Promise.all([
    minify(errorHtml, minifyOptions),
    minify(loadingHtml, minifyOptions),
    minify(spinnerHtml, minifyOptions),
  ]);

  const tsContent = `// This file is auto-generated by scripts/generate-fallback.ts
// Do not edit manually

// prettier-ignore
export const defaultErrorFallbackHtml = \`${escapeTemplate(errorMinified)}\`;

// prettier-ignore
export const defaultLoadingFallbackHtml = \`${escapeTemplate(loadingMinified)}\`;

// prettier-ignore
export const defaultSpinnerHtml = \`${escapeTemplate(spinnerMinified)}\`;
`;

  await fs.writeFile(OUTPUT_PATH, tsContent, "utf8");

  return { errorHtml, errorMinified, loadingHtml, loadingMinified, spinnerHtml, spinnerMinified };
}

// Only run when executed directly (not when imported for testing)
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/.*[\\/]/, ""))) {
  generateFallback()
    .then(
      ({
        errorHtml,
        errorMinified,
        loadingHtml,
        loadingMinified,
        spinnerHtml,
        spinnerMinified,
      }) => {
        console.log("✅ Generated:", OUTPUT_PATH);
        console.log(`   Error:   ${errorHtml.length} → ${errorMinified.length} bytes`);
        console.log(`   Loading: ${loadingHtml.length} → ${loadingMinified.length} bytes`);
        console.log(`   Spinner: ${spinnerHtml.length} → ${spinnerMinified.length} bytes`);
      },
    )
    .catch((error) => {
      console.error("❌ Failed to generate fallback:", error);
      process.exit(1);
    });
}
