import { minify } from "html-minifier-terser";
import fs from "node:fs/promises";
import path from "node:path";

const FALLBACK_HTML_PATH = path.join(import.meta.dirname, "../src/fallback.html");
const OUTPUT_PATH = path.join(import.meta.dirname, "../src/common/fallbackHtml.generated.ts");

async function generateFallback() {
  console.log("📝 Reading fallback.html...");
  const html = await fs.readFile(FALLBACK_HTML_PATH, "utf8");

  console.log("🗜️  Minifying HTML...");
  const minified = await minify(html, {
    collapseWhitespace: true,
    minifyCSS: true,
    minifyJS: true,
    removeComments: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    useShortDoctype: true,
  });

  console.log("✍️  Generating TypeScript file...");
  const tsContent = `// This file is auto-generated by scripts/generate-fallback.ts
// Do not edit manually

// prettier-ignore
export const defaultFallbackHtml = \`${minified}\`;
`;

  await fs.writeFile(OUTPUT_PATH, tsContent, "utf8");

  console.log("✅ Generated:", OUTPUT_PATH);
  console.log(`   Original size: ${html.length} bytes`);
  console.log(`   Minified size: ${minified.length} bytes`);
  console.log(
    `   Saved: ${html.length - minified.length} bytes (${Math.round((1 - minified.length / html.length) * 100)}%)`,
  );
}

generateFallback().catch((error) => {
  console.error("❌ Failed to generate fallback:", error);
  process.exit(1);
});
