import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    "philosophy",
    {
      items: [{ dirName: "getting-started", type: "autogenerated" }],
      label: "Getting Started",
      type: "category",
    },
    {
      items: [{ dirName: "spa-guard", type: "autogenerated" }],
      label: "SPA Guard",
      type: "category",
    },
    {
      items: [{ dirName: "packages", type: "autogenerated" }],
      label: "Packages",
      type: "category",
    },
    {
      items: [{ dirName: "contributing", type: "autogenerated" }],
      label: "Contributing",
      type: "category",
    },
  ],
};

export default sidebars;
