jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.32.1

      - uses: actions/setup-node@v4
        with:
          cache: pnpm

          node-version: "24"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - env:
          NODE_ENV: production
        name: Test build website
        run: pnpm turbo run website#build

name: Test Website Build

on:
  pull_request:
    branches:
      - main
